### ISSUE TITLE
Pretrained weights 

### ISSUE THREAD

**Issue by abhigoku10** [ibaiGorordo/ONNX-HybridNets-Multitask-Road-Detection#1]
@ibaiGorordo  thansk a lot for open sourcing the code base . I have one query , cna you pls share the onnx and pre trained weights it would be helpfull

THanks in advance

**Comment by ibaiGorordo** [comment]
The explanation is in the Readme. Download them from here https://drive.google.com/uc?export=download&id=1r1jDtJhi-5KfyMOee0CEbAC-N_hmf8t7 (you can find teh link in the donload.sh file in Pinto's model zoo) and place the folder in the models folder.
